### ISSUE TITLE
Compilation fails when using rascam

### ISSUE THREAD

**Issue by llamicron** [pedrosland/mmal-sys#11] opened 2023-03-28 04:47 UTC
Compilation fails when using `rascam 0.0.2` and stable `rustc 1.68.1`. See the output below. Same error appears using the nightly channel.

```
error[E0308]: mismatched types
   --> /home/llamicron/.cargo/registry/src/github.com-1ecc6299db9ec823/mmal-sys-0.1.0-3/src/lib.rs:290:35
    |
290 |             ::std::str::from_utf8(&self.camera_name).unwrap(),
    |             --------------------- ^^^^^^^^^^^^^^^^^ expected slice `[u8]`, found array `[i8; 16]`
    |             |
    |             arguments to this function are incorrect
    |
    = note: expected reference `&[u8]`
               found reference `&[i8; 16]`
note: function defined here
   --> /home/llamicron/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/converts.rs:87:14
    |
87  | pub const fn from_utf8(v: &[u8]) -> Result<&str, Utf8Error> {
    |              ^^^^^^^^^

   Compiling iana-time-zone v0.1.50
For more information about this error, try `rustc --explain E0308`.
error: could not compile `mmal-sys` due to previous error
```

**Comment by pedrosland** [comment] 2023-04-02 10:13
Hi @llamicron 
It looks like you're compiling for x86_64 architecture where there are some slight differences from Arm. Unfortunately its easy to get tripped up by this mistake and the cause isn't immediately obvious for developers new to Arm.

Probably you need to either compile on the Pi itself or cross-compile for the Pi with something like this:

```shell
rustup target add armv7-unknown-linux-gnueabihf
cargo build --release --target=armv7-unknown-linux-gnueabihf
```

Seems like a duplicate of #8. Please re-open if this does not solve the problem.

**Closed as completed by pedrosland** 2023-04-02 10:13 UTC
Labels: duplicate

**Comment by JakubKoralewski** [comment] 2023-06-21 05:58
@pedrosland, the above suggestion fixed it for me a while ago. But suddenly the issue came back. I am still specifying the same target, the target is still installed in the toolchain, but for some reason the issue is back. Tried `cargo clean`, `cargo update` and it's still there. Do you have any ideas?

EDIT: Seems to have been caused by including mmal-sys in the build-dependencies.
